task:
  name: AMD64 Linux build
  container:
    image: gcc:latest
  setup_script:
    - apt install -y cmake
  build_script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc -all)
  amd64_artifacts:
    path: "build/xtruss"

task:
  name: ARM64 Linux build
  arm_container:
    image: gcc:latest
  setup_script:
    - apt install -y cmake
  build_script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc -all)
  arm64_artifacts:
    path: "build/xtruss"